### ISSUE TITLE
#2

### ISSUE THREAD

**Issue by Hawawou** [osscameroon/hawaBot#2]
- When a new item is added into the post request, all other precedent items are still inserted into the database, making an item appear several times

**Comment by Sanix-Darker** [comment]
mhhh, i mean, it's normal...
What did you eecpect to happen ?

**Comment by Hawawou** [comment]
i was hoping for a way not to insert an ID that is already found in the database

**Comment by Sanix-Darker** [comment]
If the id is set to auto increment as a primary key, you don't have to set it in the insert's query again !
